apiVersion: v1
kind: Pod
metadata:
  name: host-path-pod
spec:
  containers:

  - name: container-1
    image: jasonljit/docker-demo:1.0.0
    volumeMounts:
    - mountPath: /tmp
      name: tmp-volume

  volumes:

  - name: tmp-volume
    hostPath:
      path: /tmp
      type: Directory
