apiVersion: v1
kind: Pod
metadata:
  name: pod-with-empty-dir
spec:
  containers:

  - image: jasonljit/docker-demo:1.0.0
    name: container-1
    ports:
    - containerPort: 3000
    volumeMounts:
    - mountPath: /cache
      name: cache-volume

  - image: jasonljit/docker-demo:1.0.2
    name: container-2
    ports:
    - containerPort: 3001
    volumeMounts:
    - mountPath: /cache
      name: cache-volume

  volumes:

  - name: cache-volume
    emptyDir: {}
