apiVersion: v1
kind: Pod
metadata:
  name: pod-with-health-check
spec:
  containers:
  - name: container-1
    image: jasonljit/docker-demo:1.0.1
    ports:
    - name: webapp-port
      containerPort: 3000
    livenessProbe:
      httpGet:
        path: /health
        port: webapp-port
      initialDelaySeconds: 5
      periodSeconds: 3
      timeoutSeconds: 3
      successThreshold: 1
      failureThreshold: 2
