apiVersion: v1
kind: Pod
metadata:
  name: pod-with-config-map
spec:
  containers:
  - name: container-1
    image: jasonljit/docker-demo:1.0.3
    ports:
    - containerPort: 3000
    volumeMounts:
    - name: my-config-volume
      mountPath: /app/config

  volumes:
  - name: my-config-volume
    configMap:
      name: my-config
